### ISSUE TITLE
Errors translating VIET?

### ISSUE THREAD

**Issue by Sourenics** [NicolasGrosjean/Translate_helper#46]
Hi again! I stepped on a "serious" problem that's happening to me. I was translating VIET, when I noticed the program was not only editing the spanish files, but also the english ones, which resulted on continous errors when trying to merge and request pulls. Since I'm noob in al this git and github thing, the only solution I found to the problem created was to delete everything and start over again.

**Comment by NicolasGrosjean** [comment]
If the English files are edited with space or empty line at line, it is normal.
The Translate Helper allow you to edit English file to fix some issues when translating.

I use [GitHub Desktop](https://desktop.github.com/) to control what changes are in committed.

With this tool, you can discard changes in English files
![image](https://user-images.githubusercontent.com/13560473/93133607-cc0c9680-f6d7-11ea-87db-93cd8f0d249d.png)

Or choose the lines you want to commit, by clicking on the lines (the blues are committed).
![image](https://user-images.githubusercontent.com/13560473/93133764-05450680-f6d8-11ea-90b1-4626e0b9304e.png)

**Comment by Sourenics** [comment]
Okay. Thanks for the explanation. And may I ask you for another thing about this git/github thing. How can I keep my fork updated? I mean, imagine I'm translating VIET and the original files get an update on the original repository, how can I update my fork then?

**Comment by Sourenics** [comment]
And another doubt, will the "No newline at the end of text" be an issue in the future? The original files have no blank line...

**Comment by NicolasGrosjean** [comment]
To keep your fork updated, you should refresh the repository by clicking on the button to synchronize your repository with Github.
![image](https://user-images.githubusercontent.com/13560473/93231474-0da14e00-f779-11ea-94b9-fae07838b552.png)

Then you should merge another branch in your branch.
![image](https://user-images.githubusercontent.com/13560473/93231550-23167800-f779-11ea-84c7-8c845c3b27e5.png)

Finally choose the upstream/master
![image](https://user-images.githubusercontent.com/13560473/93231608-36294800-f779-11ea-9781-7c96dc18ecfa.png)

For the newline at the end of the file, it is a minor issue and not so easy to fix because some files ends with empty lines some files not.
You have the issue in VIET because it is the beginning of the mod and there is new lines frequently at the end of the file but in other projects, it is rare.

**Comment by Sourenics** [comment]
Okay, I understood everything. Thanks for your efforts explaining this! It's so much clear now!
